### ISSUE TITLE
The region list is cleared

### ISSUE THREAD

**Issue by ghost** [Aquerr/WorldRebuilder#2] opened 2020-06-30 03:13 UTC
There is a bug in version 1.1.1 in which when declaring the regions and if the server will be restarted, all the configured regions are deleted

**Comment by Aquerr** [comment] 2021-04-28 07:11
Can't reproduce it. Just tested it and all regions are properly loaded after restart.

Probably WR did not load them for you because of corrupted regions file.

I am closing this issue for now as it is old. Reopen it if the issue still exists.

**Closed as completed by Aquerr** 2021-04-28 07:11 UTC
Labels: status: invalid
